[package]
authors = ["Nick Gerace <nickagerace@gmail.com>"]
categories = ["command-line-utilities", "command-line-interface"]
description = "CLI tool to help keep track of your Git repositories."
edition = "2021"
homepage = "https://nickgerace.dev"
keywords = ["git", "cli"]
license = "Apache-2.0"
name = "gfold"
readme = "README.md"
repository = "https://github.com/nickgerace/gfold/"
version = "2.0.0-rc1"

[dependencies]
anyhow = "1"
rayon = { version = "1", default-features = false }
termcolor = "1"
thiserror = "1"

[profile.release]
codegen-units = 1

# Instruct linker to optimize at the link stage.
lto = true

# This application should not panic often and only read from the filesystem.
panic = "abort"

# There is a noticeable speed difference from level 3 to 'z' or 's'.
# We need this speed for the user experience.
opt-level = 3
