name: ci
on:
  push:
    branches:
      - staging
      - trying
  pull_request:
    branches:
      - main
    paths:
      - "**.rs"
      - "Cargo.*"
      - "rustfmt.toml"
concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true
jobs:
  lint:
    name: "Nightly Fmt Check"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Do not use "rust-cache" since nightly will wipe out the cache daily
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
  test:
    name: "Clippy Lint, Test, and Build (ubuntu-latest)"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: clippy
      - uses: Swatinem/rust-cache@v1
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
      # FIXME: use cargo nextest
      - uses: actions-rs/cargo@v1
        with:
          command: test
      - uses: actions-rs/cargo@v1
        with:
          command: doc
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --locked
  build:
    name: "Build"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: Swatinem/rust-cache@v1
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --locked
