on: [push, pull_request]
name: gfold actions
jobs:

  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy
      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest,windows-latest,macos-latest]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Run cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Rename (Linux)
        if: runner.os == 'Linux'
        run: |
          cp target/release/gfold ./gfold-linux-amd64
      - name: Rename (MacOS)
        if: runner.os == 'MacOS'
        run: |
          cp target/release/gfold ./gfold-macos-amd64
      - name: Rename (Windows)
        if: runner.os == 'Windows'
        run: |
          Copy-Item target\release\gfold.exe gfold-windows-amd64.exe
      - name: Github Release
        if: github.actor == 'nickgerace'
        uses: ncipollo/release-action@v1.6.1
        with:
          tag: ${{ github.run_number }}
          artifacts: "gfold*"
          allowUpdates: "true"
          token: ${{ secrets.GITHUB_TOKEN }}
            
